### ISSUE TITLE
ReferenceError: "Dialogflow" is not defined. at detectMessageIntent(Code:xx) at onMessage(Code:xx)

### ISSUE THREAD

**Issue by gvenki** [mhawksey/Hangouts-Chat-bot-with-Dialogflow#1]
I am trying to implement Dialogue flow from my chatbot, tried exactly the same steps as given but I get a Reference error at this line., Do I have to add any library or am I missing anything?

Dialogflow.setTokenService(function(){ return goa.getToken(); } );

**Comment by gvenki** [comment]
sorry, changing application.json worked


{
  "timeZone": "Europe/London",
  "dependencies": {
    "enabledAdvancedServices": [{
      "userSymbol": "Gmail",
      "serviceId": "gmail",
      "version": "v1"
    }],
    "libraries": [{
      "userSymbol": "Dialogflow",
      "libraryId": "1G621Wm91ATQwuKtETmIr0H39UeqSXEBofL7m2AXwEkm3UypYmOuWKdCx",
      "version": "1"
    }, {
      "userSymbol": "cGoa",
      "libraryId": "1v_l4xN3ICa0lAW315NQEzAHPSoNiFdWHsMEwj2qA5t9cgZ5VWci2Qxv2",
      "version": "30"
    }]
  },
  "exceptionLogging": "STACKDRIVER",
  "chat": {
  }
}

**Comment by mhawksey** [comment]
Thanks - for others looks like the cGoa library was missing in your script

**Comment by gvenki** [comment]
am I still missing cGoa library? I think my application.json has it

**Comment by mhawksey** [comment]
Yes sorry you solved with the .json. Just confirming the solution for others :)
